### ISSUE TITLE
tv text is not searching new text files.

### ISSUE THREAD

**Issue by cozycode** [alexpasmantier/television#173] opened 2024-12-29 22:00 UTC
**Description**
I have just installed Television on my linux system and am playing around with it's text search capabilities.  It seems to search any files that existed prior to installing Television, but won't search the content of any files I have created afterwards.  I have tried with new files with no extension, with *.txt files and with *.md files.

**Expected behavior**
I was expecting the content of new files to be searched when using "tv text" to search for them. 

**Actual behavior**
Does not search within new files.

**Environment**
 - OS: Archlinux
 - Rust version: not installed
 - Project version: 
television 0.8.0
target triple: x86_64-unknown-linux-gnu
build: 1.83.0 (2024-12-29)

**Comment by alexpasmantier** [comment] 2024-12-29 23:20
I was at first really skeptical about this and then tried a couple of experiments leading me to reproducing the issue.

Turns out the problem doesn't seem to reside in newly created files but in very small files instead (which happens to often be the case of newly created files typically using `touch`), where the tiny sample buffer size I use to evaluate whether the file contains text or not was many times larger than the actual total number of bytes readeable from the file, which led to an error in calculating the proportion of printable ASCII characters.

Anyway, I don't mean to burden you with all that, nicely spotted!
Fixed in #174

**Closed** 2024-12-29 23:22 UTC
Labels: bug

**Comment by cozycode** [comment] 2024-12-29 23:57
Hey, thanks for taking a look at it and fixing it. So quickly too.  Sorry that I misdiagnosed the issue though.
